# Generated by Django 3.2.11 on 2022-01-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week4', '0002_profile_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Profile Trash',
                'verbose_name_plural': 'Profiles Trash',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('week4.profile',),
        ),
    ]
